Fix Dockerfile permission issues
On docker build after changes from:
https://github.com/kausaltech/kausal-paths/pull/46
and
https://github.com/kausaltech/kausal-paths/pull/47
there is a build error still:
```
$ podman-compose  -f docker-compose.dev.yml  -f docker-compose.yml --podman-build-args="--security-opt label=disable" up --build --build-arg INSTALL_DEV_DEPS=0 --build-arg BUILD_ID=0
...
Execution of msgfmt failed: msgfmt: error while opening "/venv/lib/python3.12/site-packages/django_filters/locale/fi/LC_MESSAGES/django.mo" for writing: Permission denied
...
CommandError: compilemessages generated one or more errors.
```

The change fixes permission errors by adding required dirs to `chown -R`
call.

After this build finally succeeds.

Note that I ran `podman-compose` because Fedora comes with `podman`, not
`docker`, yet here the behavior of `podman` and `docker` are identical.