Fix Dockerfile ARG scope
After applying changes from
https://github.com/kausaltech/kausal-paths/pull/46, Docker does not
build still.

```
$ podman-compose  -f docker-compose.dev.yml  -f docker-compose.yml --podman-build-args="--security-opt label=disable" up --build --build-arg INSTALL_DEV_DEPS=0 --build-arg BUILD_ID=0
[4/4] STEP 15/32: RUN groupadd -g ${app_user_gid} user && useradd --no-log-init -m -d /home/user -g ${app_user_gid} -u ${app_user_uid} -r user
groupadd: invalid group ID 'user'
Error: building at STEP "RUN groupadd -g ${app_user_gid} user && useradd --no-log-init -m -d /home/user -g ${app_user_gid} -u ${app_user_uid} -r user": while running runtime: exit status 3
```

The reason is incorrect scope for multiple `ARG`s:

> An ARG instruction goes out of scope at the end of the build stage
> where it was defined. To use an argument in multiple stages, each stage
> must include the ARG instruction.

(see: https://docs.docker.com/reference/dockerfile/#scope)

The change fixes the scope for all `ARG`s.

Note that I ran `podman-compose` because Fedora comes with `podman`, not
`docker`, yet here the behavior of `podman` and `docker` are identical.